### ISSUE TITLE
xlio

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk.github.io#33]

**Comment by jimharris** [comment]
worst case, very heavily fragmented receive (i.e. 4 or 8 bytes at a time)

two approaches:
1) allocate iovs for happy case, if iovs exceeded, do a realloc
2) if heavily fragmented, do a double-buffer to reduce iovs

Ben has implemented both approaches, but leans towards 1 since it is simpler. The group agreed with this approach.
